import { ScrollView, Text, View } from 'react-native';
import { ActivityItem } from '../../../components/ActivityItem';
import { Screen, SectionTitle } from '../../../components/Screen';
import { StatCard } from '../../../components/StatCard';
import { StatusBadge } from '../../../components/StatusBadge';
import { mockDashboard } from '../../../api/scrapCollector';

const stats = [['Total E-Waste', '186 kg'], ["Today's Pickups", '04'], ['Pending Requests', '12'], ['Completed', '38'], ['Total Earnings', '₹18,640']];
const bars = [55, 74, 45, 88, 63, 92, 70];

export default function CollectorDashboardScreen() {
  return <Screen title="Dashboard"><Text className="mb-4 text-base text-[#526052]">Good morning, Anil. Here is your collection pulse.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} className="-mx-5 mb-5 pl-5">{stats.map(([label, value]) => <StatCard key={label} label={label} value={value} />)}</ScrollView><View className="mb-5 rounded-3xl bg-[#2E7D32] p-5"><View className="flex-row items-start justify-between"><View><Text className="text-xs font-bold uppercase tracking-widest text-[#D9F2DC]">AI SCAN SUMMARY</Text><Text className="mt-2 text-3xl font-bold text-white">{mockDashboard.scans} scans</Text></View><Text className="text-3xl text-white">◉</Text></View><View className="mt-5 flex-row justify-between"><Text className="text-sm text-white">{mockDashboard.identified} identified</Text><Text className="text-sm text-white">{mockDashboard.recyclable} recyclable</Text><Text className="text-sm text-white">{mockDashboard.hazardous} hazardous</Text></View></View><SectionTitle action="Weekly">Collection statistics</SectionTitle><View className="mb-5 rounded-2xl border border-[#D8E8D8] bg-white p-4"><View className="h-36 flex-row items-end justify-between">{bars.map((height, index) => <View key={index} className="items-center"><View className="w-7 rounded-t-lg bg-[#62A967]" style={{ height }} /><Text className="mt-2 text-xs text-[#526052]">{['M', 'T', 'W', 'T', 'F', 'S', 'S'][index]}</Text></View>)}</View><View className="mt-4 flex-row flex-wrap"><Text className="mr-5 text-xs text-[#526052]">Electronics 42%</Text><Text className="mr-5 text-xs text-[#526052]">Metals 24%</Text><Text className="text-xs text-[#526052]">Cables 18%</Text></View></View><SectionTitle>Recent activities</SectionTitle><ActivityItem icon="✓" title="Pickup completed" detail="Green Office Hub · ₹680 earned" time="2h" /><ActivityItem icon="◉" title="New scan saved" detail="Laptop computer · 94% confidence" time="5h" /><ActivityItem icon="↗" title="Request accepted" detail="Anita Sharma · Today, 4:30 PM" time="1d" /><SectionTitle action="View all">Next pickup</SectionTitle><View className="rounded-2xl border border-[#D8E8D8] bg-white p-4"><View className="flex-row justify-between"><Text className="text-lg font-bold text-black">Anita Sharma</Text><StatusBadge status="Accepted" /></View><Text className="mt-2 text-sm text-[#526052]">Indiranagar · Laptop and cables · 4 items</Text></View></Screen>;
}
